nmct customize fix

diff --git a/stage1/90-customize-nmct/files/nmctool b/stage1/90-customize-nmct/files/nmctool
--- a/stage1/90-customize-nmct/files/nmctool
+++ b/stage1/90-customize-nmct/files/nmctool
@@ -1,3 +1,5 @@
+#!/usr/bin/env bash
+
 is_sourced(){ [[ "$0" != "$BASH_SOURCE" ]]; }
 msg(){ echo -e "$@" 1>&2; }
 err(){ msg $'\033[00;31m'"ERROR: $@"$'\033[00m'; }
@@ -5,9 +7,10 @@ die(){ err "$@"; is_sourced || exit 1 && false; }
 
 
 set_keyboard(){
-    local kb="${1:?}";
-    sudo sed -ri "/XKBLAYOUT/ s/=.*$/=\"$kb\"/" /etc/default/keyboard;
-    sudo setupcon -v
+    local kb="${1:?Missing argument: <keyboard-layout>}";
+    #sudo sed -ri "/XKBLAYOUT/ s/=.*$/=\"$kb\"/" /etc/default/keyboard;
+    #sudo setupcon -v
+    sudo raspi-config nonint do_configure_keyboard ${kb}
 }
 declare -fx set_keyboard
 
@@ -21,13 +24,13 @@ nopasswd_sudo(){
 declare -fx nopasswd_sudo
 
 set_hostname(){
-    local newname="$1"
+    local newname="${1:?Missing argument: <newname>}"
     local oldname="$(hostname)"
     [[ -n "$newname" ]] || die "No hostname specified" || return -1
     echo "Changing hostname from '$oldname' to '$newname'"
     sudo hostname "$1" && { 
-        hostname | sudo tee /etc/hostname >/dev/null
         sudo sed -i "s/$oldname/$newname/g" /etc/hosts
+        hostname | sudo tee /etc/hostname >/dev/null
         [[ -f /var/lib/cloud/seed/nocloud-net/user-data ]] && 
             sudo sed -ri "s/(hostname: ).*\$/\1$newname/" \
                 /var/lib/cloud/seed/nocloud-net/user-data
@@ -55,10 +58,10 @@ add_default_groups(){
 declare -fx add_default_groups
 
 add_user(){
-    local user="${1}"
+    local user="${1:?Missing argument: <username>}"
     [[ -n "$user" ]] || { die "Usage: $0 USERNAME" || return 1; } 
     id "$user" &>/dev/null && { die "User '$user' exists!" || return 1; }
-    sudo adduser "$user" --gecos="" --disabled-passwd 
+    sudo adduser "$user" --gecos "" --disabled-password 
     add_default_groups "$user"
     nopasswd_sudo "$user"
     sudo passwd "$user"
@@ -84,8 +87,20 @@ mkvenv(){
 }
 declare -fx mkvenv
 
+update() {
+    tmp="$(mktemp)"
+    if wget -qO "${tmp}" https://raw.githubusercontent.com/nmctseb/RPi-tools/master/nmctool; then
+        sudo install -v -m 755 "${tmp}" /usr/local/bin/nmctool
+    else
+	err "Update failed"
+	return 1
+    fi
+
+}
+
 usage(){
-    cat <<-EOF "usage: $0 <command> [<args>]
+    cat <<-EOF 
+    usage: $0 <command> [<args>]
 
     Available commands:
       add-user <name>
@@ -104,6 +119,9 @@ usage(){
       new-venv [-s] <name>
         - make a new Python3 virtual environment in <name> 
           -s: inherit system-site-packages
+      update
+	- update this tool to the latest version
+
 EOF
 }
 
@@ -117,6 +135,8 @@ is_sourced || {
         lazy-sudo)     nopasswd_sudo "$@"           ;;
         timezone)      set_timezone "$@"            ;;
         new-venv)      mkvenv "$@"                  ;;
-        *) usage;;
+	update)	       update "$@"		    ;;
+	help)	       usage "$@"		    ;;
+        *) usage 1>&2  				    ;;
     esac
 }
